baseURL = 'https://luxcook.lu/'
languageCode = 'lb'
title = 'LuxCook'
theme = 'hugo-PaperMod'


[params]
    draft = false
    ShowBreadCrumbs = true
    defaultTheme = "dark"
    author = "Niederkorn Damon"
    comments = false

    [params.homeInfoParams]
        title = "LuxCook"
        content = "Wëllkomm op LuxCook! Hei fannt Dir gutt Kachrezepter, mat engem gudde Goût!"


# for search
[outputs]
  home = ["HTML", "RSS", "JSON"]
  # https://fusejs.io/api/options.html
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys = ["title", "permalink", "summary", "content"]     