baseURL = 'https://luxcook.lu/'
title = 'LuxCook'
theme = 'hugo-PaperMod'
defaultContentLanguage = 'lb'


[params]
    draft = false
    ShowBreadCrumbs = true
    defaultTheme = "dark"
    author = "Niederkorn Damon"
    comments = false

    [params.homeInfoParams]
        title = "LuxCook"
        content = "Wëllkomm op LuxCook! Hei fannt Dir gutt Kachrezepter, mat engem gudde Goût!"

# [languages]
#     [languages.lb]
#     languageCode = "lb"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  land = "laenner"

[[menu.main]]
  identifier = "search"
  name = "Sichen"
  url = "/search/"
  weight = 40
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 30
[[menu.main]]
  identifier = "categories"
  name = "Categorie"
  url = "/categories/"
  weight = 20
[[menu.main]]
  identifier = "länner"
  name = "Länner"
  url = "/laenner/"
  weight = 10

# for search
[outputs]
  home = ["HTML", "RSS", "JSON"]
  # https://fusejs.io/api/options.html
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys = ["title", "permalink", "summary", "content"]     